import Customers from "@/components/Customers";
import MainLayout from "@/components/design/MainLayout";
import Head from "next/head";

export default function CustomersPage() {
  return (
    <>
      <Head>
        <title>SuperCar Automation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Customers />
      </MainLayout>
    </>
  );
}
