import Head from "next/head";
import Dashboard from "@/components/Dashboard";
import MainLayout from "@/components/design/MainLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>SuperCar Automation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Dashboard />
      </MainLayout>
    </>
  );
}
